project:
  type: website

website:
  title: "quarto-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Dw i ddim yn siarad Cymraeg

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



